platform :ios, "9.0"
inhibit_all_warnings!

target 'DS' do
    pod "AFNetworking"
    pod "JJFontFit"
    pod "ZLPhotoBrowser"
    pod "MJRefresh"
    pod "zhPopupController","<2.0.0"
    pod "IQKeyboardManager"
    pod "NHHUDExtend"
    pod "YYCache"
    pod "YYModel"
    pod "YYText"
    pod "JXCategoryView"
    pod "UMCCommon"
    pod "UMCSecurityPlugins"
    pod "UMCShare/Social/ReducedWeChat"
    pod "UMCShare/UI"
    pod "TYCyclePagerView"
    pod "ZLCollectionViewFlowLayout"
    pod "WechatOpenSDK","<1.8.6"
    pod 'HBDNavigationBar'
    source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
    pod 'AlibcTradeSDK','4.0.0.8'
    pod 'AliAuthSDK','2.0.0.3'
    pod 'mtopSDK','3.0.0.4'
    pod 'securityGuard','5.4.173'
    pod 'AliLinkPartnerSDK','4.0.0.24'
    pod 'BCUserTrack','5.2.0.11-appkeys'
    pod 'UTDID','1.1.0.16'
end